In [2]:
import torch

In [20]:
x = torch.empty(2,2, dtype=torch.float16)
x

tensor([[-280.0000,   -0.9082],
        [      nan,    0.0000]], dtype=torch.float16)

In [23]:
x = torch.tensor([2.5,0.1])
x

tensor([2.5000, 0.1000])

In [24]:
x,y = torch.rand(2,2), torch.rand(2,2)
x,y

(tensor([[0.5112, 0.3394],
         [0.2834, 0.5411]]),
 tensor([[0.5938, 0.6768],
         [0.7872, 0.9783]]))

In [26]:
z = x+y
z

tensor([[1.1050, 1.0162],
        [1.0706, 1.5195]])

In [27]:
z = torch.add(x,y)
z

tensor([[1.1050, 1.0162],
        [1.0706, 1.5195]])

In [28]:
y.add_(x)
y

tensor([[1.1050, 1.0162],
        [1.0706, 1.5195]])

In [34]:
x = torch.rand(5,3)
print(x)
print(x[2,:])

tensor([[0.1166, 0.1681, 0.1921],
        [0.8976, 0.2218, 0.6198],
        [0.1092, 0.8773, 0.2803],
        [0.5150, 0.1380, 0.8001],
        [0.0602, 0.7351, 0.2649]])
tensor([0.1092, 0.8773, 0.2803])


In [35]:
x = torch.rand(4,4)
y = x.view(16)
y

tensor([0.8607, 0.4835, 0.6989, 0.6316, 0.2543, 0.3820, 0.7830, 0.7530, 0.8297,
        0.8503, 0.6102, 0.4722, 0.0027, 0.9136, 0.6226, 0.3682])

In [36]:
y = x.view(-1,8)
y

tensor([[0.8607, 0.4835, 0.6989, 0.6316, 0.2543, 0.3820, 0.7830, 0.7530],
        [0.8297, 0.8503, 0.6102, 0.4722, 0.0027, 0.9136, 0.6226, 0.3682]])

In [37]:
y.size()

torch.Size([2, 8])

In [38]:
import numpy as np

a = torch.ones(5)
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [39]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [40]:
a = np.ones(5)
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)