In [1]:
import torch 
import numpy as np

In [3]:
#tensors are numpy arrays 
data = [[1,2],[3,4]]
x_d = torch.tensor(data)
#torch.tensor array to tensor

In [4]:
npa = np.array(data)
x_np = torch.tensor(npa)

In [7]:
xo = torch.ones_like(x_d)
print(f"Ones tensor: \n {xo}")

Ones tensor: 
 tensor([[1, 1],
        [1, 1]])


In [11]:
xr = torch.rand_like(x_d, dtype=torch.float)
print(f"Random Tensor:\n {xr}")
#ones like and rand like take args as dtype & shape. shape above is x_d

Random Tensor:
 tensor([[0.8042, 0.5767],
        [0.9862, 0.7518]])


In [21]:
#shape is a tuple of tensor dimensions
# first arg in tuple is row, 2nd is col for 2d data
# for 3d & above 1st arg is the biggest array, containing an array of 2nd arg 
# which contains an array of 3rd arg on so on till the n-1 array. 
# and the nth array are element nested in n-1 array.
shape = (1,3,5,2,1)
rt = torch.rand(shape)
ot = torch.ones(shape)
zt = torch.zeros(shape)

print(f" Random tensor : \n {rt} ")
print(f" Oners tensor : \n {ot} ")
print(f" Zeroes tensor : \n {zt} ")

 Random tensor : 
 tensor([[[[[0.6886],
           [0.0775]],

          [[0.8540],
           [0.9275]],

          [[0.5028],
           [0.6824]],

          [[0.5737],
           [0.8261]],

          [[0.9815],
           [0.5553]]],


         [[[0.8451],
           [0.6913]],

          [[0.1099],
           [0.1849]],

          [[0.0518],
           [0.6276]],

          [[0.9972],
           [0.5422]],

          [[0.1505],
           [0.1856]]],


         [[[0.5853],
           [0.4829]],

          [[0.3994],
           [0.7394]],

          [[0.6473],
           [0.3693]],

          [[0.2919],
           [0.0114]],

          [[0.7240],
           [0.3276]]]]]) 
 Oners tensor : 
 tensor([[[[[1.],
           [1.]],

          [[1.],
           [1.]],

          [[1.],
           [1.]],

          [[1.],
           [1.]],

          [[1.],
           [1.]]],


         [[[1.],
           [1.]],

          [[1.],
           [1.]],

          [[1.],
           [1.]],

      

In [22]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [30]:
tensor = torch.rand(2,3,4)
print(tensor)

print('First row: ',tensor[0])
#sorts through first arg in shape tuple


print('First col: ',tensor[:,0])
# print('First row: ',tensor[..., -1])
# tensor[:,1] = 0


tensor([[[0.0554, 0.9403, 0.0212, 0.1669],
         [0.1307, 0.9906, 0.0897, 0.8741],
         [0.4480, 0.8410, 0.7232, 0.0701]],

        [[0.5257, 0.4249, 0.1368, 0.6388],
         [0.7635, 0.2232, 0.5429, 0.8603],
         [0.6709, 0.7650, 0.5857, 0.9459]]])
First row:  tensor([[0.0554, 0.9403, 0.0212, 0.1669],
        [0.1307, 0.9906, 0.0897, 0.8741],
        [0.4480, 0.8410, 0.7232, 0.0701]])
First col:  tensor([[0.0554, 0.9403, 0.0212, 0.1669],
        [0.5257, 0.4249, 0.1368, 0.6388]])


In [39]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

#return 3 els from array
print(arr[1:5:2])

#return 1st item and a gap of n specified so for below 0 3 6 items
print(arr[::3])

# no of elements from start reqd
print(arr[:5])

#no of elements to leave from start
print(arr[5:])

# n elements to leave from end
print(arr[:-2])

#els from first to last arg
print(arr[2:4])



[2 4]
[1 4 7]
[1 2 3 4 5]
[6 7]
[1 2 3 4 5]


In [48]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])

#slice from first nested array
print(a[1:])

#get item at s arg indx for each row
print('sd',a[...,1])

# ell els at f arg indx
print('td', a[1,...])

# all item in arg are removed from each col
print(a[...,1:])

[[3 4 5]
 [4 5 6]]
sd [2 4 5]
td [3 4 5]
[[2 3]
 [4 5]
 [5 6]]


In [52]:
#joining tensors
# works like append, data shall be same shape, 
#joins along axis of second arg in 3d data
# joins along elements in 2d array
tensor = torch.rand(2,2,2)
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[[0.7604, 0.4256],
         [0.9791, 0.8250],
         [0.7604, 0.4256],
         [0.9791, 0.8250],
         [0.7604, 0.4256],
         [0.9791, 0.8250]],

        [[0.9887, 0.7294],
         [0.1465, 0.8618],
         [0.9887, 0.7294],
         [0.1465, 0.8618],
         [0.9887, 0.7294],
         [0.1465, 0.8618]]])


In [56]:
tensor = torch.rand(2,2)
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(tensor)
print(tensor)
print(y1)
print(y2)
print(y3)
#y1 & y2 have the same value they prob multiply tensor with tensor.T

tensor([[0.1579, 0.0217],
        [0.0742, 0.1254]])
tensor([[0.0254, 0.0144],
        [0.0144, 0.0212]])
tensor([[0.0254, 0.0144],
        [0.0144, 0.0212]])
tensor([[0.9796, 0.8699],
        [0.4400, 0.4698]])


In [58]:
tensor = torch.rand(2,3)
t2 = tensor.T
print(tensor)
print(t2)
#tensor.T switches rows with columns

tensor([[0.9485, 0.7494, 0.5606],
        [0.4606, 0.9769, 0.9011]])
tensor([[0.9485, 0.4606],
        [0.7494, 0.9769],
        [0.5606, 0.9011]])


In [60]:
tensor = torch.rand(1,2,3)
t2 = tensor.T
print(tensor)
print(t2)
#tensor.T switches rows with columns
# in tranposing 3d & above arrays we go opposite direction 
# like example above so we will go from (1,2,3) array to (3,2,1)

tensor([[[0.4541, 0.5572, 0.4305],
         [0.9152, 0.8217, 0.2200]]])
tensor([[[0.4541],
         [0.9152]],

        [[0.5572],
         [0.8217]],

        [[0.4305],
         [0.2200]]])


In [63]:
tensor = torch.rand(1,2,3)
y0 = tensor * tensor.T

In [67]:
print(y0)

tensor([[[0.0479, 0.0075, 0.0891],
         [0.0405, 0.0254, 0.0113]],

        [[0.0075, 0.0012, 0.0140],
         [0.0254, 0.0159, 0.0070]],

        [[0.0891, 0.0140, 0.1657],
         [0.0113, 0.0070, 0.0031]]])


In [72]:
tensor = torch.rand(3,2)

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
print(tensor)
print(y1)
print(y2)

tensor([[0.3925, 0.0338],
        [0.9452, 0.2725],
        [0.7955, 0.3024]])
tensor([[0.1552, 0.3802, 0.3225],
        [0.3802, 0.9676, 0.8343],
        [0.3225, 0.8343, 0.7242]])
tensor([[0.1552, 0.3802, 0.3225],
        [0.3802, 0.9676, 0.8343],
        [0.3225, 0.8343, 0.7242]])


In [77]:
tensor = torch.rand(1,3,5)
t1 = tensor.T

In [78]:
print(tensor)
print(t1)

tensor([[[0.0310, 0.7313, 0.8306, 0.4735, 0.7266],
         [0.5642, 0.6906, 0.0296, 0.3960, 0.3238],
         [0.7353, 0.6043, 0.6385, 0.5561, 0.3495]]])
tensor([[[0.0310],
         [0.5642],
         [0.7353]],

        [[0.7313],
         [0.6906],
         [0.6043]],

        [[0.8306],
         [0.0296],
         [0.6385]],

        [[0.4735],
         [0.3960],
         [0.5561]],

        [[0.7266],
         [0.3238],
         [0.3495]]])
